### PR TITLE
Added a dropdown field type to allow the user to select a form.

### PR DESCRIPTION
**Pull request by joshangell**
Also extended the variable to include getFormById().

### CODE REVIEW

**Comment by owldesign** [comment]
Hi, do you think you can provide usage example for this? 

Thanks!

**Comment by joshangell** [comment]
Yeah of course - sorry!

To allow the user to place a form we usually have a block type in a matrix for forms and then let them pick from a drop down. However, if we allow users to create and manage forms as well then it is handy to auto-populate that drop down.

Of course there is a debate as to whether or not to allow users to manage forms, but we often do want them to. Aside from that it's useful to not have to maintain a separate set of options in drop down field.

Hope that makes some kind of sense!

**Comment by owldesign** [comment]
This is interesting. I haven't played around with custom field types yet, this is a good start. Thanks!

**Comment by joshangell** [comment]
No problem!

**Pull request merged**
